/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finasys.forms.administration;

import com.google.common.collect.Lists;
import finasys.forms.administration.AddUserForm;
import finasys.FinaSys;
import finasys.User;
import finasys.managers.UserManager;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author giddyc
 */
public final class AdministrationForm extends javax.swing.JInternalFrame {

    private static AdministrationForm instance;
    private List<UUID> uuids;
    public static AdministrationForm getInstance() {
        if (instance == null) {
            instance = new AdministrationForm();
        }
        return instance;
    }

    /**
     * Creates new form AdministrationForm
     */
    protected AdministrationForm() {
        this.uuids = Lists.newArrayList();
        initComponents();
//        TableModel tm = new UserTableModel();
//        userTable.setModel(tm);
//        userTable.
        updateUserList();
        removeUserBtn.setEnabled(false);
        editUserBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addUserBtn = new javax.swing.JButton();
        removeUserBtn = new javax.swing.JButton();
        editUserBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("FinaSys Administration");
        setMaximumSize(new java.awt.Dimension(406, 376));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Controls"));

        addUserBtn.setText("Add User");
        addUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserBtnActionPerformed(evt);
            }
        });

        removeUserBtn.setText("Remove User");
        removeUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeUserBtnActionPerformed(evt);
            }
        });

        editUserBtn.setText("Edit User");
        editUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserBtnActionPerformed(evt);
            }
        });

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addUserBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editUserBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeUserBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(addUserBtn)
                .addComponent(removeUserBtn)
                .addComponent(editUserBtn)
                .addComponent(refreshBtn))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("FinaSys Users"));
        jPanel2.setToolTipText("");

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Username", "Access Level"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(userTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        updateUserList();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void addUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserBtnActionPerformed
        AddUserForm form = new AddUserForm();
        form.setVisible(true);
        form.setLocation(FinaSys.centreFrame(form));
        finasys.MainFrame.getDesktop().add(form);
        try {
            form.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        }

    }//GEN-LAST:event_addUserBtnActionPerformed

    private void removeUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeUserBtnActionPerformed
        int index = userTable.getSelectedRow();
        String username = (String) userTable.getValueAt(index, 0);
        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove " + username + "?");
        if (option == JOptionPane.YES_OPTION) {
            UserManager.getInstance().removeUser(uuids.get(index));
        }
        updateUserList();
    }//GEN-LAST:event_removeUserBtnActionPerformed

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        int row = userTable.getSelectedRow();
        if (row != -1) {
            removeUserBtn.setEnabled(true);
            editUserBtn.setEnabled(true);
        }
    }//GEN-LAST:event_userTableMouseClicked

    private void editUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserBtnActionPerformed
        int index = userTable.getSelectedRow();
        EditUserForm form = new EditUserForm();
        form.setUser(UserManager.getInstance().getUsers().get(uuids.get(index)));
        form.setVisible(true);
        form.setLocation(FinaSys.centreFrame(form));
        finasys.MainFrame.getDesktop().add(form);
        try {
            form.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        }

    }//GEN-LAST:event_editUserBtnActionPerformed

    public void updateUserList() {
        uuids = Lists.newArrayList(UserManager.getInstance().getUsers().keySet());
        List<User> users = Lists.newArrayList(UserManager.getInstance().getUsers().values());
        UserTableModel tm = new UserTableModel(users);
        tm.setRowCount(users.size());
        userTable.setModel(tm);
    }

    private static class UserTableModel extends DefaultTableModel {

        private final String[] columnNames = {"Username", "Access Level"};
        private final Object[][] data;

        public UserTableModel(List<User> users) {
            if (users == null || users.isEmpty()) { // NULL CHECK 
                data = new Object[][]{};
                return;
            }
            data = new Object[users.size()][2];
            for (int i = 0; i < users.size(); i++) {
                data[i][0] = users.get(i).getUsername();
                data[i][1] = users.get(i).getAccessLevel();
            }
        }

        @Override
        public String getColumnName(int col) {
            return columnNames[col];
        }

        @Override
        public int getColumnCount() {
            return columnNames.length;
        }

        @Override
        public Object getValueAt(int row, int col) {
            return data[row][col];
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserBtn;
    private javax.swing.JButton editUserBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton removeUserBtn;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
